[package]
name = "greatway"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
bytes = "1.7.2"
dotenv = "0.15.0"
futures-util = "0.3.30"
http = "1.1.0"
reqwest = { version = "0.12.7", features = ["json", "stream"] }
